const KEY = 'patrimoine_pilot_merged_v1';
const euro = new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 });
const pct = new Intl.NumberFormat('fr-FR', { style: 'percent', maximumFractionDigits: 1 });

const initialState = {
  theme: 'dark', activeSub: { dashboard: 'synthese', plan: 'versements', actions: 'alertes' },
  profile: { ageRange: '26-35 ans', monthlySalary: 3200, tmi: 30, horizon: 30, savingCapacity: 800 },
  targets: { per: 300, pea: 250, avModern: 200, avBnp: 50 },
  actualContributions: { per: 300, pea: 250, avModern: 0, avBnp: 50 },
  projection: { monthly: 800, returnRate: 6, horizon: 30, annualIncrease: 2 },
  realEstate: { value: 200000, mortgage: 92000, ptz: 54000, monthlyPayment: 690, futureRent: 900, charges: 100, propertyTax: 100 },
  assets: [
    { id:'pea', name:'PEA', opened:'2019', balance:16700, ytd:6.2, tax:'Fiscalité PEA > 5 ans', allocation:'ETF actions', history:[13800,14150,14400,14880,15100,15350,15750,16020,16220,16400,16600,16700], holdings:[
      ['Amundi PEA MSCI World',7156,'LU1681043599'], ['Amundi PEA S&P 500',4858,'LU1681048804'], ['Amundi PEA MSCI Émergents ESG',2471,'LU2008215762'], ['BNP Easy Stoxx Europe 600',2206,'LU1437018838']
    ]},
    { id:'livretA', name:'Livret A', opened:'—', balance:22700, ytd:3.0, tax:'Exonéré', allocation:'Cash sécurisé', history:[22000,22100,22200,22280,22350,22420,22500,22560,22610,22650,22690,22700] },
    { id:'avBnp', name:'AV BNP Multiplacements Avenir', opened:'2008', balance:172, ytd:1.0, tax:'AV > 8 ans', allocation:'Ancienne AV', history:[170,170,171,171,171,172,172,172,172,172,172,172] },
    { id:'per', name:'PER', opened:'2026', balance:1000, ytd:0.8, tax:'Déductible TMI 30 %', allocation:'Retraite', history:[0,0,0,0,0,0,0,0,250,500,750,1000] },
    { id:'current', name:'Compte courant', opened:'—', balance:1200, ytd:0, tax:'Disponible', allocation:'Liquidité', history:[1100,1350,900,1500,1200,1400,1000,1300,1100,1250,1180,1200] }
  ],
  checklist: {},
  snapshots: []
};
const checklistGroups = [
  { id:'week', title:'🔥 Cette semaine', items:['Vérifier contrainte PTZ avant mise en location','Ouvrir / comparer Lucya Cardif','Analyser les frais AV BNP','Verrouiller budget mensuel'] },
  { id:'month', title:'📅 Ce mois', items:['Mettre en place versement PER','Programmer virements automatiques','Préparer versement PER 3 800 €','Étudier transfert PACTE','Souscrire PNO'] },
  { id:'quarter', title:'📆 Dans 3 mois', items:['Contacter expert-comptable LMNP','Finaliser meubles et inventaire','Trouver locataire','Vérifier INPI / SIRET LMNP','Comparer GLI'] },
  { id:'year', title:'🗓️ Dans l’année', items:['Préparer déclaration LMNP','Faire bilan patrimonial annuel','Consulter CGP si arbitrage complexe'] }
];
let state = load();
let currentTab = 'dashboard';
let charts = {};

function clone(x){ return JSON.parse(JSON.stringify(x)); }
function load(){ try { return { ...clone(initialState), ...(JSON.parse(localStorage.getItem(KEY)) || {}) }; } catch { return clone(initialState); } }
function save(){ localStorage.setItem(KEY, JSON.stringify(state)); updateBadges(); }
function fmt(v){ return euro.format(Math.round(v || 0)); }
function totalLiquid(){ return state.assets.reduce((s,a)=>s+Number(a.balance||0),0); }
function totalAssets(){ return totalLiquid() + state.realEstate.value; }
function totalDebts(){ return state.realEstate.mortgage + state.realEstate.ptz; }
function netWorth(){ return totalAssets() - totalDebts(); }
function totalTargets(){ return Object.values(state.targets).reduce((a,b)=>a+Number(b||0),0); }
function taxSavingsAnnual(){ return state.targets.per * 12 * state.profile.tmi / 100; }
function cashFlowLmnp(){ return state.realEstate.futureRent - state.realEstate.charges - state.realEstate.propertyTax - state.realEstate.monthlyPayment; }
function assetShare(v){ return totalAssets() ? pct.format(v / totalAssets()) : '—'; }
function esc(s){ return String(s ?? '').replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])); }

function topbar(title, sub){ return `<header class="topbar"><div class="brand"><h1>${title}</h1><p>${sub}</p></div><div class="top-actions"><button class="icon-btn" onclick="saveSnapshot()" aria-label="Snapshot"><i data-lucide="save"></i></button></div></header>`; }
function stat(label, value, note=''){ return `<article class="stat"><span>${label}</span><strong>${value}</strong>${note?`<small>${note}</small>`:''}</article>`; }
function setTab(tab){ currentTab = tab; document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active', b.dataset.tab===tab)); render(); }
function setSub(page, sub){ state.activeSub[page]=sub; save(); render(); }

function alerts(){ const arr=[]; const cash=state.assets.find(a=>a.id==='livretA')?.balance||0; if(cash>15000) arr.push({level:'orange',title:'Cash élevé sur Livret A',text:'Redéploiement prévu : 12 700 € sur 12 mois vers PER, PEA et AV moderne.'}); if((state.actualContributions.avModern||0)<state.targets.avModern) arr.push({level:'red',title:'AV moderne non alimentée',text:'Objectif mensuel : 200 €. Action à planifier.'}); if(state.targets.per*12>=3600) arr.push({level:'green',title:'PER cohérent avec la TMI',text:`Économie fiscale annuelle estimée : ${fmt(taxSavingsAnnual())}.`}); if(cashFlowLmnp()>0) arr.push({level:'green',title:'LMNP futur positif',text:`Cash-flow estimé : ${fmt(cashFlowLmnp())}/mois après mensualité, charges et taxe foncière.`}); return arr; }
function checklistProgress(){ let done=0,total=0; checklistGroups.forEach(g=>g.items.forEach((_,i)=>{total++; if(state.checklist[`${g.id}-${i}`]) done++;})); return {done,total,progress: total?Math.round(done/total*100):0}; }
function updateBadges(){ const a=alerts().filter(x=>x.level!=='green').length; const p=checklistProgress(); const ab=document.getElementById('alertBadge'); if(ab){ab.textContent=a;ab.classList.toggle('show',a>0)} const pb=document.getElementById('planBadge'); if(pb){pb.textContent=Math.max(0,100-p.progress);pb.classList.toggle('show',p.progress<100)} }

function render(){ destroyCharts(); document.documentElement.classList.toggle('light', state.theme==='light'); if(currentTab==='dashboard') renderDashboard(); if(currentTab==='assets') renderAssets(); if(currentTab==='plan') renderPlan(); if(currentTab==='actions') renderActions(); if(currentTab==='profile') renderProfile(); setTimeout(()=>{ renderChartsForTab(); if(window.lucide) lucide.createIcons(); updateBadges(); },0); }
function tabs(page, items){ const active=state.activeSub[page]||items[0][0]; return `<div class="section-tabs">${items.map(([id,label])=>`<button class="tab-chip ${active===id?'active':''}" onclick="setSub('${page}','${id}')">${label}</button>`).join('')}</div>`; }

function renderDashboard(){ const p=checklistProgress(); document.getElementById('screen').innerHTML = `${topbar('Patrimoine Pilot','Vue d’ensemble mobile')}
<section class="hero"><div class="eyebrow">Patrimoine net</div><div class="hero-value">${fmt(netWorth())}</div><div class="hero-row"><span class="badge green">Épargne ${fmt(state.profile.savingCapacity)}/mois</span><span class="badge ${p.progress>60?'green':'yellow'}">Actions ${p.progress}%</span></div><div class="actions"><button class="btn primary" onclick="setTab('assets')">Mettre à jour</button><button class="btn secondary" onclick="setTab('plan')">Voir le plan</button></div></section>
<div class="grid2">${stat('Total actifs',fmt(totalAssets()),'liquide + immobilier')}${stat('Total dettes',fmt(totalDebts()),'crédit + PTZ')}${stat('Capacité',fmt(state.profile.savingCapacity),'/ mois')}${stat('Impôts économisés',fmt(taxSavingsAnnual()),'PER annuel estimé')}</div>
${tabs('dashboard',[['synthese','Synthèse'],['perf','Performance'],['allocation','Allocation']])}<div id="dashSub"></div>`; const sub=state.activeSub.dashboard||'synthese'; document.getElementById('dashSub').innerHTML = sub==='synthese'?`<article class="card chart-card"><div class="card-head"><h2>Évolution 12 mois</h2><span class="badge blue">mini-chart</span></div><div class="chart-wrap"><canvas id="netMini"></canvas></div></article><article class="card"><div class="card-head"><h2>Décision du mois</h2><span class="badge yellow">Priorité</span></div><p class="helper">Réduire progressivement le surplus du Livret A, activer l’AV moderne et conserver le PER pour profiter de la TMI à 30 %.</p></article>`: sub==='perf'?`<div class="grid3">${stat('TRI estimé','6,1 %','approximation')}${stat('YTD global','4,4 %','pondéré')}${stat('Drawdown max','-8,7 %','simulé')}</div><article class="card chart-card"><h2>Vs MSCI World</h2><div class="chart-wrap"><canvas id="benchmark"></canvas></div></article>`:`<article class="card chart-card"><div class="card-head"><h2>Allocation actuelle</h2><span class="badge green">vs cible</span></div><div class="chart-wrap"><canvas id="allocation"></canvas></div></article>`; }

function renderAssets(){ document.getElementById('screen').innerHTML = `${topbar('Actifs','Patrimoine détaillé')}
<section class="hero"><div class="eyebrow">Total actifs</div><div class="hero-value">${fmt(totalAssets())}</div><div class="hero-row"><span class="badge blue">Liquidités ${fmt(totalLiquid())}</span><span class="badge green">Immo ${fmt(state.realEstate.value)}</span></div></section>
${state.assets.map(assetCard).join('')}<article class="card"><div class="card-head"><h2>Immobilier</h2><span class="badge yellow">LMNP futur</span></div><div class="asset-details"><div class="detail"><span>Valeur</span><strong>${fmt(state.realEstate.value)}</strong></div><div class="detail"><span>Crédit</span><strong>${fmt(state.realEstate.mortgage)}</strong></div><div class="detail"><span>PTZ</span><strong>${fmt(state.realEstate.ptz)}</strong></div><div class="detail"><span>Loyer futur</span><strong>${fmt(state.realEstate.futureRent)}/mois</strong></div><div class="detail"><span>Cash-flow</span><strong>${fmt(cashFlowLmnp())}/mois</strong></div><div class="detail"><span>% patrimoine</span><strong>${assetShare(state.realEstate.value)}</strong></div></div></article>`; bindAssetInputs(); }
function assetCard(a){ return `<article class="asset-card"><div class="asset-head"><div><h3>${esc(a.name)}</h3><p class="sub">Ouverture : ${esc(a.opened)} · ${esc(a.tax)}</p></div><div class="asset-value"><strong>${fmt(a.balance)}</strong><span class="badge ${a.ytd>=0?'green':'red'}">YTD ${a.ytd.toFixed(1)}%</span></div></div>${a.holdings?`<div class="asset-tags">${a.holdings.map(h=>`<span class="badge blue">${esc(h[0])} · ${fmt(h[1])}</span>`).join('')}</div>`:''}<div class="asset-details"><div class="detail"><span>Solde éditable</span><input class="field" type="number" value="${a.balance}" data-asset="${a.id}"></div><div class="detail"><span>% patrimoine</span><strong>${assetShare(a.balance)}</strong></div><div class="detail"><span>Allocation</span><strong>${esc(a.allocation)}</strong></div><div class="detail"><span>Historique</span><canvas id="spark-${a.id}" width="120" height="34"></canvas></div></div></article>`; }
function bindAssetInputs(){ document.querySelectorAll('[data-asset]').forEach(inp=>inp.addEventListener('change',e=>{ const a=state.assets.find(x=>x.id===e.target.dataset.asset); a.balance=Number(e.target.value||0); a.history=[...(a.history||[]).slice(-11),a.balance]; save(); render(); })); }

function renderPlan(){ const active=state.activeSub.plan||'versements'; document.getElementById('screen').innerHTML = `${topbar('Plan','Objectifs, versements et projections')}${tabs('plan',[['versements','Versements'],['plafonds','Plafonds'],['projection','Projection']])}<div id="planSub"></div>`; const el=document.getElementById('planSub'); if(active==='versements') el.innerHTML=`<article class="card"><h2>Objectif vs réel</h2>${goal('PER',state.actualContributions.per,state.targets.per)}${goal('PEA',state.actualContributions.pea,state.targets.pea)}${goal('AV moderne',state.actualContributions.avModern,state.targets.avModern)}${goal('AV BNP',state.actualContributions.avBnp,state.targets.avBnp)}</article><article class="card chart-card"><div class="card-head"><h2>Redéploiement Livret A</h2><span class="badge green">12 mois</span></div><div class="chart-wrap"><canvas id="redeploy"></canvas></div></article>`; if(active==='plafonds') el.innerHTML=`<article class="card"><h2>Plafonds & fiscalité</h2>${goal('PER annuel',state.targets.per*12,3840,`${fmt(taxSavingsAnnual())} économie impôt`)}${goal('PEA',state.assets.find(a=>a.id==='pea').balance,150000,'Plafond indicatif')}${goal('AV abattement',0,4600,'Après 8 ans')}${goal('Redéploiement Livret A',0,12700,'Sur 12 mois')}</article>`; if(active==='projection') el.innerHTML=`<article class="card"><h2>Hypothèses</h2><div id="projectionControls"></div></article><div class="grid2"><article class="stat"><span>Date million</span><strong id="millionDate">—</strong></article><article class="stat"><span>Capital projeté</span><strong id="projectedCapital">—</strong></article><article class="stat"><span>Rente 4 %</span><strong id="retirementIncome">—</strong></article><article class="stat"><span>Économie fiscale</span><strong id="taxSavingsProjected">—</strong></article></div><article class="card chart-card"><h2>Courbe de croissance</h2><div class="chart-wrap tall"><canvas id="projection"></canvas></div></article>`; if(active==='projection') renderProjectionControls(); }
function goal(label,value,target,note=''){ const r=target?Math.min(value/target,1)*100:0; return `<div class="goal-row"><header><strong>${label}</strong><span>${fmt(value)} / ${fmt(target)}</span></header><div class="progress"><span style="width:${r}%"></span></div><small class="sub">${note||Math.round(r)+' % atteint'}</small></div>`; }
function renderProjectionControls(){ const ctr=[['monthly','Versement mensuel',0,3000,'€'],['returnRate','Rendement annuel',0,12,'%'],['horizon','Horizon',1,40,'ans'],['annualIncrease','Hausse annuelle',0,8,'%']]; document.getElementById('projectionControls').innerHTML=ctr.map(([k,l,min,max,s])=>`<div class="control-row"><header><strong>${l}</strong><span id="val-${k}">${state.projection[k]} ${s}</span></header><input type="range" min="${min}" max="${max}" step="${k==='returnRate'||k==='annualIncrease'?0.1:1}" value="${state.projection[k]}" data-proj="${k}" data-suffix="${s}"></div>`).join(''); document.querySelectorAll('[data-proj]').forEach(i=>i.addEventListener('input',e=>{state.projection[e.target.dataset.proj]=Number(e.target.value); document.getElementById('val-'+e.target.dataset.proj).textContent=e.target.value+' '+e.target.dataset.suffix; save(); renderProjectionResults(); drawProjection();})); renderProjectionResults(); }
function projectionSeries(){ let capital=netWorth(), monthly=state.projection.monthly, out=[capital]; for(let y=1;y<=state.projection.horizon;y++){ for(let m=0;m<12;m++) capital=(capital+monthly)*(1+state.projection.returnRate/100/12); out.push(capital); monthly*=1+state.projection.annualIncrease/100; } return out; }
function renderProjectionResults(){ const arr=projectionSeries(); const million=arr.findIndex(x=>x>=1000000); const years=arr.length-1; document.getElementById('millionDate').textContent=million>0?`Dans ${million} ans`:'Non atteint'; document.getElementById('projectedCapital').textContent=fmt(arr.at(-1)); document.getElementById('retirementIncome').textContent=fmt(arr.at(-1)*.04); document.getElementById('taxSavingsProjected').textContent=fmt(taxSavingsAnnual()*years); }

function renderActions(){ const p=checklistProgress(); const active=state.activeSub.actions||'alertes'; document.getElementById('screen').innerHTML=`${topbar('Actions','Alertes et checklist')}${tabs('actions',[['alertes','Alertes'],['checklist','Checklist']])}<div id="actionsSub"></div>`; const el=document.getElementById('actionsSub'); if(active==='alertes') el.innerHTML=alerts().map(a=>`<article class="alert-card ${a.level}"><div class="card-head"><h3>${esc(a.title)}</h3><span class="badge ${a.level==='red'?'red':a.level==='green'?'green':'yellow'}">${a.level}</span></div><p>${esc(a.text)}</p></article>`).join(''); else el.innerHTML=`<article class="card"><div class="card-head"><h2>Avancement global</h2><strong>${p.progress}%</strong></div><div class="progress"><span style="width:${p.progress}%"></span></div></article>${checklistGroups.map(g=>`<article class="card check-card"><h2>${g.title}</h2>${g.items.map((it,i)=>{const k=`${g.id}-${i}`;return `<label><input type="checkbox" data-check="${k}" ${state.checklist[k]?'checked':''}><span>${esc(it)}</span></label>`}).join('')}</article>`).join('')}`; document.querySelectorAll('[data-check]').forEach(c=>c.addEventListener('change',e=>{state.checklist[e.target.dataset.check]=e.target.checked; save(); render();})); }

function renderProfile(){ document.getElementById('screen').innerHTML=`${topbar('Profil','Paramètres et sauvegarde')}
<article class="card"><h2>Profil</h2><div class="form-grid">${field('Salaire net mensuel','profile','monthlySalary',state.profile.monthlySalary)}${field('TMI (%)','profile','tmi',state.profile.tmi)}${field('Horizon (années)','profile','horizon',state.profile.horizon)}${field('Capacité épargne','profile','savingCapacity',state.profile.savingCapacity)}</div></article>
<article class="card"><h2>Objectifs mensuels</h2><div class="form-grid">${field('PER','targets','per',state.targets.per)}${field('PEA','targets','pea',state.targets.pea)}${field('AV moderne','targets','avModern',state.targets.avModern)}${field('AV BNP','targets','avBnp',state.targets.avBnp)}</div></article>
<article class="card"><h2>Backup local</h2><div class="backup-actions"><button class="btn primary" onclick="exportJson()">Exporter JSON</button><label class="btn secondary file-label">Importer JSON<input type="file" id="importInput" accept="application/json" hidden></label><button class="btn secondary" onclick="toggleTheme()">Mode sombre / clair</button><button class="btn danger" onclick="resetApp()">Reset</button></div><p class="muted">Stockage localStorage. Aucune connexion bancaire, aucun backend.</p></article>`; document.querySelectorAll('[data-field]').forEach(i=>i.addEventListener('change',e=>{state[e.target.dataset.scope][e.target.dataset.field]=Number(e.target.value||0); save(); render();})); document.getElementById('importInput').addEventListener('change',importJson); }
function field(label,scope,key,value){ return `<div><label class="field-label">${label}</label><input class="field" type="number" value="${value}" data-scope="${scope}" data-field="${key}"></div>`; }
function toggleTheme(){ state.theme=state.theme==='dark'?'light':'dark'; save(); render(); }
function resetApp(){ if(confirm('Réinitialiser toutes les données locales ?')){ state=clone(initialState); save(); render(); } }
function exportJson(){ const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='patrimoine-pilot-backup.json'; a.click(); URL.revokeObjectURL(a.href); toast('Backup exporté'); }
function importJson(e){ const file=e.target.files[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{ try{ state={...clone(initialState),...JSON.parse(r.result)}; save(); render(); toast('Backup importé'); }catch{ toast('JSON invalide'); } }; r.readAsText(file); }
function saveSnapshot(){ state.snapshots.push({date:new Date().toISOString().slice(0,10),netWorth:netWorth(),assets:totalAssets(),debts:totalDebts()}); state.snapshots=state.snapshots.slice(-24); save(); render(); toast('Snapshot enregistré'); }
function toast(msg){ const t=document.getElementById('toast'); t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),1800); }

function destroyCharts(){ Object.values(charts).forEach(c=>c?.destroy?.()); charts={}; }
function chartOptions(){ return {responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:getComputedStyle(document.documentElement).getPropertyValue('--muted')}}},scales:{x:{ticks:{color:'#8b93a5'},grid:{color:'rgba(255,255,255,.06)'}},y:{ticks:{color:'#8b93a5'},grid:{color:'rgba(255,255,255,.06)'}}}}; }
function newChart(id,type,data,options={}){ const el=document.getElementById(id); if(!el||!window.Chart)return; charts[id]=new Chart(el,{type,data,options:{...chartOptions(),...options}}); }
function renderChartsForTab(){ if(!window.Chart)return; if(currentTab==='dashboard'){ if(document.getElementById('netMini')) newChart('netMini','line',{labels:Array.from({length:12},(_,i)=>`M-${11-i}`),datasets:[{label:'Patrimoine net',data:(state.snapshots.length>=2?state.snapshots.map(s=>s.netWorth):Array.from({length:12},(_,i)=>netWorth()-totalTargets()*(11-i))),tension:.35,fill:true}]}); if(document.getElementById('benchmark')) newChart('benchmark','line',{labels:['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'],datasets:[{label:'Patrimoine',data:[100,101,102,103,102,104,106,107,108,109,111,112],tension:.35},{label:'MSCI World',data:[100,101,100,103,105,104,106,108,107,110,111,113],tension:.35}]}); if(document.getElementById('allocation')) drawAllocation(); } if(currentTab==='assets') drawSparks(); if(currentTab==='plan'){ if(document.getElementById('redeploy')) newChart('redeploy','bar',{labels:Array.from({length:12},(_,i)=>`M${i+1}`),datasets:[{label:'Redéploiement cumulé',data:Array.from({length:12},(_,i)=>Math.round(12700/12*(i+1)))}]}); if(document.getElementById('projection')) drawProjection(); } }
function drawAllocation(){ const liquid=totalLiquid(), immo=state.realEstate.value, debt=totalDebts(); newChart('allocation','doughnut',{labels:['ETF / enveloppes','Immobilier','Dettes'],datasets:[{data:[liquid,immo,debt]}]},{scales:{},cutout:'62%'}); }
function drawProjection(){ const el=document.getElementById('projection'); if(!el)return; if(charts.projection) charts.projection.destroy(); const arr=projectionSeries(); charts.projection=new Chart(el,{type:'line',data:{labels:arr.map((_,i)=>i),datasets:[{label:'Capital projeté',data:arr,tension:.32,fill:true}]},options:chartOptions()}); }
function drawSparks(){ state.assets.forEach(a=>{ const el=document.getElementById('spark-'+a.id); if(!el||!window.Chart)return; charts['spark-'+a.id]=new Chart(el,{type:'line',data:{labels:(a.history||[]).map((_,i)=>i+1),datasets:[{data:a.history||[],borderWidth:2,pointRadius:0,tension:.35}]},options:{responsive:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}}}}); }); }

document.addEventListener('DOMContentLoaded',()=>{ document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>setTab(btn.dataset.tab))); render(); });
window.setTab=setTab; window.setSub=setSub; window.saveSnapshot=saveSnapshot; window.exportJson=exportJson; window.toggleTheme=toggleTheme; window.resetApp=resetApp;
